gin:
  # gin_mode: debug
  gin_mode: release
  skip_paths: ['/metrics']

server:
  address: :8080
  read_timeout: 10s
  write_timeout: 10s

tokens:
  access_expiration: 30m
  refresh_expiration: 48h

kafka:
  brokers:
    - "kafka:29092"
  topic: "login-events"
