global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"
  body_size_limit: "0"
  sample_limit: 0
  label_limit: 0
  label_name_length_limit: 0
  label_value_length_limit: 0
  target_limit: 0

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8080']
    metrics_path: /metrics

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
