env: "release" # debug

server:
  address: ":8081"
  read_timeout: 5s
  write_timeout: 10s

smtp_host: "smtp.gmail.com" 
smtp_port: 587

kafka:
  brokers:
    - "kafka:29092"
  topic: "login-events"
  consumer_group: "email-service" 