#!/bin/bash

ENV_FILE=".env"

POSTGRES_USER="jerey"
POSTGRES_PASSWORD="jereyjerey"
POSTGRES_HOST="postgres"
POSTGRES_PORT="5432"
POSTGRES_DB="auth_database"
SECRET_KEY=$(openssl rand -hex 32)

echo "POSTGRES_USER=${POSTGRES_USER}" > $ENV_FILE
echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> $ENV_FILE
echo "POSTGRES_HOST=${POSTGRES_HOST}" >> $ENV_FILE
echo "POSTGRES_PORT=${POSTGRES_PORT}" >> $ENV_FILE
echo "POSTGRES_DB=${POSTGRES_DB}" >> $ENV_FILE
echo "SECRET_KEY=${SECRET_KEY}" >> $ENV_FILE
